### ISSUE TITLE
README.md : Install link is not working

### ISSUE THREAD

**Issue by Mukta-Sawant** [DeEgge/openeats#3]
The link provided in the install guide is showing an error.
https://blog.kuntzsch.me/setting-up-a-self-hosted-recipe-management-site-openeats/

**Comment by chringel21** [comment]
This fork is kind of old, and I long abandoned my blog. Please refer to the updated version at https://github.com/open-eats/OpenEats. Unfortunately, they only provide installation instructions using docker. But you might be able figure stuff out from reading the docker files.

Best of luck!
